### PR TITLE
Fix q3map2 pak sorting

### LINKED ISSUE #614: q3map2 vfs does not reverse pak list upon dir initialization
The game and Radiant load files in descending order, this way paks with higher number will always be loaded first, and first registered file with the same name always has precedence over the next one, when it comes to loading contents, but q3map2 loads files in ascending order instead! 
Could someone explain, is this by design?

The issue appears specifically here:
https://github.com/TTimo/GtkRadiant/blob/2d91146b804be2d3176880d1a491dda96c4f92a7/tools/quake3/common/vfs.c#L198
While radiant's vfs does the sorting:
https://github.com/TTimo/GtkRadiant/blob/2d91146b804be2d3176880d1a491dda96c4f92a7/plugins/vfspk3/vfs.cpp#L464

Now this might be not a big issue, but actually, this can bring to some really weird results.

Like here, where `pak1.pk3` contains yellow walls, and `pak2.pk3` red ones. Q3map2 uses `pak1.pk3` to lit the surface, and game loads `pak2.pk3` to display the texture!

wrong light

And Radiant loads `pak2.pk3` as expected:

radiant

If we leave just `pak2.pk3`, we would get something we expect to get:

right light

### PR DESCRIPTION
**Pull request by isRyven**
* Copied over sorting function from radiant's vfs
* Adapted directory initialization code to run sorting

Tested on map, works good so far. No optimization was done to reduce number of iterations, but i don't want to break anything.

closes #614

### CODE REVIEW

File: tools/quake3/common/vfs.c [hunk 1]
```diff
@@ -188,38 +231,48 @@ void vfsInitDirectory( const char *path ){
...
-				sprintf( filename, "%s/%s", path, dirlist );
-				vfsInitPakFile( filename );
+				if ( ext != NULL && ( !Q_stricmp( ext, ".pk3" ) || !Q_stricmp( ext, ".dpk" )) ) {
+					sprintf(filename, "%s/%s", path, name);
+					vfsInitPakFile(filename);
+				}
 
-				g_free( dirlist );
+				g_free(name);
+				dirlist = g_slist_remove(cur, name);
```
Comment (TTimo) [inline tools/quake3/common/vfs.c]: Is a little safer to free after the list remove, but that should be ok.

Comment (isRyven) [reply tools/quake3/common/vfs.c]: Oops 😁 thanks for fixing that!
