### PR TITLE
Fix build error on Linux due to missing `<stdint.h>` include

### LINKED ISSUE #662: Build error on Fedora 33: ‘uintptr_t’ undeclared (first use in this function)
**OS:** Fedora 33 x86_64
**GtkRadiant version:** Git https://github.com/TTimo/GtkRadiant/commit/46abf34850c670ad3dc9f4f1c6233bef2ccead41
**SCons version:** 4.0.1 from pip, running on Python 3.9.0

Running `scons target="q3map2,q3data"` gives me the following:

```
❯ scons target="q3map2,q3data"
scons: Reading SConscript files ...
reading saved configuration from site.conf
saving updated configuration
emit build rules
emit configuration: config: target=['q3map2', 'q3data', ''] config=['release']
parse /home/hugo/Documents/Git/TTimo/GtkRadiant/tools/quake3/common/quake3-common.vcxproj
10 source files
parse /home/hugo/Documents/Git/TTimo/GtkRadiant/libs/mathlib/mathlib.vcxproj
4 source files
parse /home/hugo/Documents/Git/TTimo/GtkRadiant/libs/l_net/l_net.vcxproj
2 source files
parse /home/hugo/Documents/Git/TTimo/GtkRadiant/libs/ddslib/ddslib.vcxproj
1 source files
parse /home/hugo/Documents/Git/TTimo/GtkRadiant/libs/picomodel/picomodel.vcxproj
23 source files
parse /home/hugo/Documents/Git/TTimo/GtkRadiant/libs/md5lib/md5lib.vcxproj
2 source files
parse /home/hugo/Documents/Git/TTimo/GtkRadiant/tools/quake3/q3map2/q3map2.vcxproj
44 source files
parse /home/hugo/Documents/Git/TTimo/GtkRadiant/tools/quake3/common/quake3-common.vcxproj
10 source files
parse /home/hugo/Documents/Git/TTimo/GtkRadiant/libs/mathlib/mathlib.vcxproj
4 source files
parse /home/hugo/Documents/Git/TTimo/GtkRadiant/libs/l_net/l_net.vcxproj
2 source files
parse /home/hugo/Documents/Git/TTimo/GtkRadiant/libs/ddslib/ddslib.vcxproj
1 source files
parse /home/hugo/Documents/Git/TTimo/GtkRadiant/libs/picomodel/picomodel.vcxproj
23 source files
parse /home/hugo/Documents/Git/TTimo/GtkRadiant/libs/md5lib/md5lib.vcxproj
2 source files
parse /home/hugo/Documents/Git/TTimo/GtkRadiant/tools/urt/tools/quake3/q3map2/q3map2_urt.vcxproj
38 source files
parse /home/hugo/Documents/Git/TTimo/GtkRadiant/libs/mathlib/mathlib.vcxproj
4 source files
parse /home/hugo/Documents/Git/TTimo/GtkRadiant/libs/l_net/l_net.vcxproj
2 source files
parse /home/hugo/Documents/Git/TTimo/GtkRadiant/libs/ddslib/ddslib.vcxproj
1 source files
parse /home/hugo/Documents/Git/TTimo/GtkRadiant/tools/quake3/q3data/q3data.vcxproj
19 source files
scons: done reading SConscript files.
scons: Building targets ...
gcc -o build/release/q3map2/tools/quake3/common/threads.o -c -O2 -fno-strict-aliasing -pipe -Wall -fmessage-length=0 -fvisibility=hidden -I/usr/include/libxml2 -DQ_NO_STLPORT -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -Ibuild/release/q3map2/include -Iinclude -Ibuild/release/q3map2/libs -Ilibs tools/quake3/common/threads.c
tools/quake3/common/threads.c: In function ‘RunThreadsOn’:
tools/quake3/common/threads.c:555:70: error: ‘uintptr_t’ undeclared (first use in this function)
  555 |    if ( pthread_create( &work_threads[i], NULL, (void*)func, (void*)(uintptr_t)i ) != 0 ) {
      |                                                                      ^~~~~~~~~
tools/quake3/common/threads.c:555:70: note: each undeclared identifier is reported only once for each function it appears in
tools/quake3/common/threads.c:555:80: error: expected ‘)’ before ‘i’
  555 |    if ( pthread_create( &work_threads[i], NULL, (void*)func, (void*)(uintptr_t)i ) != 0 ) {
      |                                                                                ^
      |                                                                                )
scons: *** [build/release/q3map2/tools/quake3/common/threads.o] Error 1
scons: building terminated because of errors.
```

(I only want q3map2, not the rest of GtkRadiant.)

After a quick search, I noticed this error was mentioned in passing in https://github.com/TTimo/GtkRadiant/issues/574#issuecomment-383378571 but I figured it'd be good to have a dedicated issue for it.

### PR DESCRIPTION
**Pull request by Calinou**
This closes #662.

**Note:** Only tested on Linux/GCC, not other compilers.

I get another error when continuing the build, but I still get a working `q3map2` binary in the `install` folder:

```
❯ scons target="q3map2,q3data"
scons: Reading SConscript files ...
reading saved configuration from site.conf
saving updated configuration
emit build rules
emit configuration: config: target=['q3map2', 'q3data', ''] config=['release']
parse /home/hugo/Documents/Git/TTimo/GtkRadiant/tools/quake3/common/quake3-common.vcxproj
10 source files
parse /home/hugo/Documents/Git/TTimo/GtkRadiant/libs/mathlib/mathlib.vcxproj
4 source files
parse /home/hugo/Documents/Git/TTimo/GtkRadiant/libs/l_net/l_net.vcxproj
2 source files
parse /home/hugo/Documents/Git/TTimo/GtkRadiant/libs/ddslib/ddslib.vcxproj
1 source files
parse /home/hugo/Documents/Git/TTimo/GtkRadiant/libs/picomodel/picomodel.vcxproj
23 source files
parse /home/hugo/Documents/Git/TTimo/GtkRadiant/libs/md5lib/md5lib.vcxproj
2 source files
parse /home/hugo/Documents/Git/TTimo/GtkRadiant/tools/quake3/q3map2/q3map2.vcxproj
44 source files
parse /home/hugo/Documents/Git/TTimo/GtkRadiant/tools/quake3/common/quake3-common.vcxproj
10 source files
parse /home/hugo/Documents/Git/TTimo/GtkRadiant/libs/mathlib/mathlib.vcxproj
4 source files
parse /home/hugo/Documents/Git/TTimo/GtkRadiant/libs/l_net/l_net.vcxproj
2 source files
parse /home/hugo/Documents/Git/TTimo/GtkRadiant/libs/ddslib/ddslib.vcxproj
1 source files
parse /home/hugo/Documents/Git/TTimo/GtkRadiant/libs/picomodel/picomodel.vcxproj
23 source files
parse /home/hugo/Documents/Git/TTimo/GtkRadiant/libs/md5lib/md5lib.vcxproj
2 source files
parse /home/hugo/Documents/Git/TTimo/GtkRadiant/tools/urt/tools/quake3/q3map2/q3map2_urt.vcxproj
38 source files
parse /home/hugo/Documents/Git/TTimo/GtkRadiant/libs/mathlib/mathlib.vcxproj
4 source files
parse /home/hugo/Documents/Git/TTimo/GtkRadiant/libs/l_net/l_net.vcxproj
2 source files
parse /home/hugo/Documents/Git/TTimo/GtkRadiant/libs/ddslib/ddslib.vcxproj
1 source files
parse /home/hugo/Documents/Git/TTimo/GtkRadiant/tools/quake3/q3data/q3data.vcxproj
19 source files
scons: done reading SConscript files.
scons: Building targets ...
scons: `install/q3map2' is up to date.
scons: `install/q3map2_urt' is up to date.
scons: `install/q3data' is up to date.
FinishBuild(["finish"], [])
Lookup and bundle the PNG and JPEG libraries
ldd: install/modules/image.so: No such file or directory
ldd failed with error code 1 and output:b''
scons: *** [finish] AssertionError : 
Traceback (most recent call last):
  File "/home/hugo/Documents/Git/TTimo/GtkRadiant/config.py", line 414, in FinishBuild
    module_ldd = subprocess.check_output( ['ldd', '-r', 'install/modules/image.so'] ).decode( 'utf-8' )
  File "/home/hugo/.pyenv/versions/3.9.0/lib/python3.9/subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/home/hugo/.pyenv/versions/3.9.0/lib/python3.9/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ldd', '-r', 'install/modules/image.so']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hugo/.pyenv/versions/3.9.0/lib/python3.9/site-packages/SCons/Action.py", line 1280, in execute
    result = self.execfunction(target=target, source=rsources, env=env)
  File "/home/hugo/Documents/Git/TTimo/GtkRadiant/config.py", line 417, in FinishBuild
    assert( False )
AssertionError
scons: building terminated because of errors.
```

I suppose it's not related to the original bug report.

### CODE REVIEW

File: tools/quake3/common/threads.c [hunk 1]
```diff
@@ -26,6 +26,8 @@
 #include <pthread.h>
 #endif
 
+#include <stdint.h>
```
Comment (tkoeppe) [inline tools/quake3/common/threads.c:29]: If this is only needed for uintptr_t below, then maybe move this inclusion to line 435?

Comment (Calinou) [reply tools/quake3/common/threads.c:29]: It seems strange to me to use an `#include` at the middle of a file.

Comment (tkoeppe) [reply tools/quake3/common/threads.c:29]: Well, true, but this is already what's done here, and given that this file contains arch-specific conditional compilation, it is perhaps not entirely unsurprising.
